// Code generated by tygo. DO NOT EDIT.

import { Unit } from './units';

//////////
// source: dtos.go

export interface CreateUpdateRecipeDTO {
  title: string;
  url?: string;
  tags: string[];
  ingredients: CreateRecipeIngredientDTO[];
  servings?: number /* uint */;
  description?: string;
  headline?: string;
  steps?: string;
  prepTime?: number /* uint */;
}

export interface CreateRecipeIngredientDTO {
  quantity: number /* float64 */;
  unit: Unit;
  name: string;
}

//////////
// source: model.go

export interface Recipe {
  id: string /* uuid */;
  title: string;
  headline?: string;
  description?: string;
  steps?: string;
  servings?: number /* uint */;
  prepTime?: number /* uint */;
  url?: string;
  tags: string[];
  ingredients: RecipeIngredient[];
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
}

export interface RecipeIngredient {
  id: string /* uuid */;
  name: string;
  kind?: string;
  unit: Unit;
  amount: number /* float64 */;
}

//////////
// source: router.go

export interface RecipeWithoutIngredients {
  id: string /* uuid */;
  title: string;
  headline?: string;
  createdAt: string /* RFC3339 */;
  updatedAt: string /* RFC3339 */;
  description?: string;
  steps?: string;
  servings?: number /* uint */;
  prepTime?: number /* uint */;
  url?: string;
  tags: string[];
  slug: string;
}

export interface GetRecipesResponse {
  recipes: RecipeWithoutIngredients[];
}

export interface CreateUpdateRecipeRequest extends CreateUpdateRecipeDTO {}

export interface CreateRecipeResponse extends Recipe {
  slug: string;
}

export interface GetRecipeResponse extends Recipe {
  slug: string;
}

export interface UpdateRecipeResponse extends Recipe {
  slug: string;
}
