// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID        string
	Name      string
	Kind      *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Recipe struct {
	ID          string
	Title       string
	Headline    *string
	Description *string
	Steps       *string
	Servings    *int32
	PrepTime    *int32
	Url         *string
	Tags        []string
	Slug        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RecipeIngredient struct {
	RecipeID     string
	IngredientID string
	Unit         string
	Quantity     float64
}

type RecipeTag struct {
	RecipeID string
	Tag      interface{}
}
