// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recipes.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO
  ingredients (name, kind)
VALUES 
  ($1, $2)
RETURNING
  id, name, kind, created_at, updated_at
`

type CreateIngredientParams struct {
	Name string
	Kind *string
}

func (q *Queries) CreateIngredient(ctx context.Context, db DBTX, arg CreateIngredientParams) (Ingredient, error) {
	row := db.QueryRow(ctx, createIngredient, arg.Name, arg.Kind)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO
  recipes (id, title, slug, headline, description, steps, prep_time, servings, url, tags)
VALUES 
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
  id, title, headline, description, steps, servings, prep_time, url, tags, slug, created_at, updated_at
`

type CreateRecipeParams struct {
	ID          string
	Title       string
	Slug        string
	Headline    *string
	Description *string
	Steps       *string
	PrepTime    *int32
	Servings    *int32
	Url         *string
	Tags        []string
}

func (q *Queries) CreateRecipe(ctx context.Context, db DBTX, arg CreateRecipeParams) (Recipe, error) {
	row := db.QueryRow(ctx, createRecipe,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Headline,
		arg.Description,
		arg.Steps,
		arg.PrepTime,
		arg.Servings,
		arg.Url,
		arg.Tags,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Headline,
		&i.Description,
		&i.Steps,
		&i.Servings,
		&i.PrepTime,
		&i.Url,
		&i.Tags,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeIngredient = `-- name: CreateRecipeIngredient :execrows
INSERT INTO
recipe_ingredients (recipe_id, ingredient_id, unit, quantity) 
VALUES 
($1, $2, $3, $4)
`

type CreateRecipeIngredientParams struct {
	RecipeID     string
	IngredientID string
	Unit         string
	Quantity     float64
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, db DBTX, arg CreateRecipeIngredientParams) (int64, error) {
	result, err := db.Exec(ctx, createRecipeIngredient,
		arg.RecipeID,
		arg.IngredientID,
		arg.Unit,
		arg.Quantity,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes
WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, db DBTX, id string) (int64, error) {
	result, err := db.Exec(ctx, deleteRecipe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipeIngredients = `-- name: DeleteRecipeIngredients :execrows
DELETE FROM recipe_ingredients
WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeIngredients(ctx context.Context, db DBTX, recipeID string) (int64, error) {
	result, err := db.Exec(ctx, deleteRecipeIngredients, recipeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, title, headline, description, steps, servings, prep_time, url, tags, slug, created_at, updated_at FROM recipes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecipeByID(ctx context.Context, db DBTX, id string) (Recipe, error) {
	row := db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Headline,
		&i.Description,
		&i.Steps,
		&i.Servings,
		&i.PrepTime,
		&i.Url,
		&i.Tags,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeBySlug = `-- name: GetRecipeBySlug :one
SELECT id, title, headline, description, steps, servings, prep_time, url, tags, slug, created_at, updated_at FROM recipes
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetRecipeBySlug(ctx context.Context, db DBTX, slug string) (Recipe, error) {
	row := db.QueryRow(ctx, getRecipeBySlug, slug)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Headline,
		&i.Description,
		&i.Steps,
		&i.Servings,
		&i.PrepTime,
		&i.Url,
		&i.Tags,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeIngredients = `-- name: GetRecipeIngredients :many
SELECT 
  i.id, i.name, i.kind, ri.unit, ri.quantity
FROM 
recipe_ingredients ri 
LEFT JOIN 
  ingredients i ON i.id = ri.ingredient_id 
WHERE 
ri.recipe_id = $1
`

type GetRecipeIngredientsRow struct {
	ID       pgtype.UUID
	Name     *string
	Kind     *string
	Unit     string
	Quantity float64
}

func (q *Queries) GetRecipeIngredients(ctx context.Context, db DBTX, recipeID string) ([]GetRecipeIngredientsRow, error) {
	rows, err := db.Query(ctx, getRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeIngredientsRow
	for rows.Next() {
		var i GetRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Unit,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, title, headline, description, steps, servings, prep_time, url, tags, slug, created_at, updated_at FROM recipes ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context, db DBTX) ([]Recipe, error) {
	rows, err := db.Query(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Headline,
			&i.Description,
			&i.Steps,
			&i.Servings,
			&i.PrepTime,
			&i.Url,
			&i.Tags,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE 
  recipes 
SET
  title = $1,
  slug = $2,
  headline = $3,
  description = $4,
  steps = $5,
  prep_time = $6,
  servings = $7,
  url = $8,
  tags = $9
WHERE 
  id = $10
RETURNING
  id, title, headline, description, steps, servings, prep_time, url, tags, slug, created_at, updated_at
`

type UpdateRecipeParams struct {
	Title       string
	Slug        string
	Headline    *string
	Description *string
	Steps       *string
	PrepTime    *int32
	Servings    *int32
	Url         *string
	Tags        []string
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, db DBTX, arg UpdateRecipeParams) (Recipe, error) {
	row := db.QueryRow(ctx, updateRecipe,
		arg.Title,
		arg.Slug,
		arg.Headline,
		arg.Description,
		arg.Steps,
		arg.PrepTime,
		arg.Servings,
		arg.Url,
		arg.Tags,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Headline,
		&i.Description,
		&i.Steps,
		&i.Servings,
		&i.PrepTime,
		&i.Url,
		&i.Tags,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIngredient = `-- name: UpsertIngredient :one
INSERT INTO ingredients (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE 
SET name = EXCLUDED.name
RETURNING id, name, kind, created_at, updated_at
`

func (q *Queries) UpsertIngredient(ctx context.Context, db DBTX, name string) (Ingredient, error) {
	row := db.QueryRow(ctx, upsertIngredient, name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
