// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: suggestions.sql

package sql

import (
	"context"
)

const findAllIngredients = `-- name: FindAllIngredients :many
SELECT name AS value FROM ingredients ORDER BY name ASC
`

func (q *Queries) FindAllIngredients(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.Query(ctx, findAllIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTags = `-- name: FindAllTags :many
SELECT DISTINCT
tag::text AS value
FROM
  recipe_tags
ORDER BY
  tag ASC
`

func (q *Queries) FindAllTags(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.Query(ctx, findAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMatchingIngredients = `-- name: FindMatchingIngredients :many
SELECT value, score
FROM (
SELECT
  name AS value, similarity(name, $1::text) as score
FROM
ingredients
ORDER BY 
score DESC
) AS matches
WHERE
score >= $2::float
`

type FindMatchingIngredientsParams struct {
	Search    string
	Threshold float64
}

type FindMatchingIngredientsRow struct {
	Value string
	Score float32
}

func (q *Queries) FindMatchingIngredients(ctx context.Context, db DBTX, arg FindMatchingIngredientsParams) ([]FindMatchingIngredientsRow, error) {
	rows, err := db.Query(ctx, findMatchingIngredients, arg.Search, arg.Threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindMatchingIngredientsRow
	for rows.Next() {
		var i FindMatchingIngredientsRow
		if err := rows.Scan(&i.Value, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMatchingTags = `-- name: FindMatchingTags :many
SELECT DISTINCT value::text, score
FROM (
  SELECT
tag AS value, similarity(tag, $1::text) as score
FROM
  recipe_tags
  ORDER BY
  score DESC
) AS matches
WHERE
  score >= $2::float
`

type FindMatchingTagsParams struct {
	Search    string
	Threshold float64
}

type FindMatchingTagsRow struct {
	Value string
	Score float32
}

func (q *Queries) FindMatchingTags(ctx context.Context, db DBTX, arg FindMatchingTagsParams) ([]FindMatchingTagsRow, error) {
	rows, err := db.Query(ctx, findMatchingTags, arg.Search, arg.Threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindMatchingTagsRow
	for rows.Next() {
		var i FindMatchingTagsRow
		if err := rows.Scan(&i.Value, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
