/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as RecipesCreateImport } from './routes/recipes/create'
import { Route as RecipesRecipeIdOrSlugImport } from './routes/recipes/$recipeIdOrSlug'

// Create/Update Routes

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesCreateRoute = RecipesCreateImport.update({
  id: '/recipes/create',
  path: '/recipes/create',
  getParentRoute: () => rootRoute,
} as any)

const RecipesRecipeIdOrSlugRoute = RecipesRecipeIdOrSlugImport.update({
  id: '/recipes/$recipeIdOrSlug',
  path: '/recipes/$recipeIdOrSlug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipes/$recipeIdOrSlug': {
      id: '/recipes/$recipeIdOrSlug'
      path: '/recipes/$recipeIdOrSlug'
      fullPath: '/recipes/$recipeIdOrSlug'
      preLoaderRoute: typeof RecipesRecipeIdOrSlugImport
      parentRoute: typeof rootRoute
    }
    '/recipes/create': {
      id: '/recipes/create'
      path: '/recipes/create'
      fullPath: '/recipes/create'
      preLoaderRoute: typeof RecipesCreateImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/recipes/$recipeIdOrSlug': typeof RecipesRecipeIdOrSlugRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesByTo {
  '/recipes/$recipeIdOrSlug': typeof RecipesRecipeIdOrSlugRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes': typeof RecipesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/recipes/$recipeIdOrSlug': typeof RecipesRecipeIdOrSlugRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/': typeof RecipesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/recipes/$recipeIdOrSlug' | '/recipes/create' | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to: '/recipes/$recipeIdOrSlug' | '/recipes/create' | '/recipes'
  id: '__root__' | '/recipes/$recipeIdOrSlug' | '/recipes/create' | '/recipes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RecipesRecipeIdOrSlugRoute: typeof RecipesRecipeIdOrSlugRoute
  RecipesCreateRoute: typeof RecipesCreateRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  RecipesRecipeIdOrSlugRoute: RecipesRecipeIdOrSlugRoute,
  RecipesCreateRoute: RecipesCreateRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/recipes/$recipeIdOrSlug",
        "/recipes/create",
        "/recipes/"
      ]
    },
    "/recipes/$recipeIdOrSlug": {
      "filePath": "recipes/$recipeIdOrSlug.tsx"
    },
    "/recipes/create": {
      "filePath": "recipes/create.tsx"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
