// Code generated by tygo. DO NOT EDIT.

import { Unit } from '../recipes/units';

//////////
// source: model.go

export interface Recipe {
  title: string;
  ingredients: {
    name: string;
    quantity: number /* float64 */;
    unit: Unit;
  }[];
  tags: string[];
  servings: number /* int */;
  steps: string[];
  description: string;
  headline: string;
  prepTime: number /* int */;
}

//////////
// source: router.go

export interface CompleteRecipeRequest {
  url: string;
}

export interface CompleteRecipeResponse {
  recipe: Recipe;
}
